name: Deploy to Dokku
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning repo 
      uses: actions/checkout@v2
      with:
        fetch-dept: 0 
    - name: Push to dokku
      uses: obrassard/action-dokku-deploy@master
      with:
       dokku_repo: ${{ secrets.DOKKU_REPO }}
       ssh_key: ${{ secrets.PRIVATE_KEY }}
